version: "3.1"
services:
    db:
        image: mysql
        restart: always
        ports:
          - 3306:3306
        environment:
          MYSQL_ROOT_PASSWORD: admin

    adminer:
        image: adminer
        restart: always
        ports:
          - 8080:8080        
      
    app-host:
        image: httpd
        restart: always
        ports:
          - 8081:80
        volumes:
          - ./source:/usr/local/apache2/htdocs/
